language: rust
rust:
  - stable
cache: cargo
sudo: required
group: deprecated-2017Q2
dist: trusty
env:
  global:
    - CLIPPY_VERS=0.0.131
    - RUSTFMT_VERS=0.8.4
before_install:
- rustup toolchain install nightly
script:
- cargo test
- ./nightly-test.sh
