language: rust
rust:
  - stable
  - nightly
cache: cargo
sudo: required
group: deprecated-2017Q2
dist: trusty
env:
  global:
    - NIGHTLY_RUST=nightly-2017-05-10
    - CLIPPY_VERS=0.0.131
    - RUSTFMT_VERS=0.8.4
before_install:
- rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
- rustup toolchain install $NIGHTLY_RUST
- cargo +$NIGHTLY_RUST clippy -V | grep $CLIPPY_VERS || cargo +$NIGHTLY_RUST install clippy --vers $CLIPPY_VERS --force
- sudo add-apt-repository -y ppa:elt/libsodium
- sudo apt-get -qq update
- cargo install --list
- cargo-audit -V || cargo install cargo-audit --force
install:
- sudo apt-get -qq --yes install gcc g++ make libsodium-dev libleveldb-dev libssl-dev
script:
- cargo audit
- cargo test
- ./hightly-test.sh
