language: rust
rust:
  - stable
cache: cargo
sudo: required
group: deprecated-2017Q2
dist: trusty
env:
  global:
    - NIGHTLY_RUST=nightly-2017-05-10
    - CLIPPY_VERS=0.0.131
    - RUSTFMT_VERS=0.8.4
before_install:
- rustup toolchain install $NIGHTLY_RUST
script:
- cargo test
- ./nightly-test.sh
